all:
   hosts:
   vars:
      ansible_user: zvv
#      ansible_ssh_user: ansible
      ansible_become_user: root
      ansible_become_method: sudo
#      ansible_ssh_private_key_file: user_private_key
   children:
      app:
        children:
        vars:
        hosts:
            vm2:
               ansible_host: 158.160.57.253
            vm3:
               ansible_host: 158.160.110.7
      database:
        children:
        vars:
          postgresql_version: 11
          postgresql_data_directory: /opt/pgsql/data
        hosts:
            vm1:
               ansible_host: 158.160.43.216
      web:
         hosts:
            vm1:      

         




